In [6]:
import pandas as pd

data = {'Name': ["John", "Anna", "Peter", "Linda"],
        'Location' : ["New York", "Paris", "Berlin", "London"],
        'Age' : [24, 13, 53, 33]
       }

data_pandas = pd.DataFrame(data)
# IPython.display allows "pretty printing" of dataframes
# in the Jupyter notebook
display(data_pandas)

Age  Location   Name
0   24  New York   John
1   13     Paris   Anna
2   53    Berlin  Peter
3   33    London  Linda

In [7]:
import sys
print("Python version: {}".format(sys.version))

import pandas as pd
print("pandas version: {}".format(pd.__version__))

import matplotlib
print("matplotlib version: {}".format(matplotlib.__version__))

import numpy as np
print("NumPy version: {}".format(np.__version__))

import scipy as sp
print("SciPy version: {}".format(sp.__version__))

import IPython
print("IPython version: {}".format(IPython.__version__))

import sklearn
print("scikit-learn version: {}".format(sklearn.__version__))



Python version: 3.6.1 |Anaconda custom (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
pandas version: 0.20.1
matplotlib version: 2.0.2
NumPy version: 1.12.1
SciPy version: 0.19.0
IPython version: 6.0.0
scikit-learn version: 0.18.1


In [8]:
from sklearn.datasets import load_iris
iris_dataset = load_iris(
)

In [9]:
print("{}".format(iris_dataset.keys()))

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [11]:
print(iris_dataset['DESCR'][:192])

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive at


In [12]:
print(iris_dataset['DESCR'][:193
                    ])

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive att


In [13]:
print(iris_dataset['DESCR'][:192]+"\n...")

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive at
...


In [14]:
print("first five columns of data:\n{}".format(iris_dataset['data'][:5]))

first five columns of data:
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]


In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'],random_state=0)

In [16]:
print("{}".format(X_train.shape))
print("{}".format(Y_train.shape
                ))

(112, 4)
(112,)


In [17]:
from sklearn.neighbors import KNeighborsClassifier as KN
knn = KN(n_neighbors=1
        )

In [19]:
knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [20]:
x,y = mglearn.dataserts.make_forge()

NameError: name 'mglearn' is not defined

In [1]:
google=10**100
google

10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [2]:
google* google

100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [3]:
'cracle'

'cracle'

In [4]:
'''poem
poek
poek'''

'poem\npoek\npoek'

In [5]:
'poem
poek
poek'

SyntaxError: EOL while scanning string literal (<ipython-input-5-3e6be597d115>, line 1)

In [6]:
'''poem'''

'poem'

In [7]:
'''poem
    poek
            poek'''

'poem\n    poek\n            poek'

In [8]:
a=1
a


1

In [9]:
a+=1
a

2

In [10]:
b+=1
b

NameError: name 'b' is not defined

In [11]:
a=['b','c','ef']

In [12]:
a.split(',')

AttributeError: 'list' object has no attribute 'split'

In [13]:
','.join(a)

'b,c,ef'

In [14]:
print(','.join(a)
     )

b,c,ef


In [15]:
setup = 'a duck goes into a bar...'

In [16]:
setup

'a duck goes into a bar...'

In [17]:
print(setup
     )

a duck goes into a bar...


In [18]:
setup.strip('.')

'a duck goes into a bar'

In [19]:
setup.capitalize

<function str.capitalize>

In [20]:
setup.capitalize()


'A duck goes into a bar...'

In [21]:
 setup.title()

'A Duck Goes Into A Bar...'

In [22]:
setup.upper()

'A DUCK GOES INTO A BAR...'

In [23]:
setup.center(30)

'  a duck goes into a bar...   '

In [24]:
setup.right(30)

AttributeError: 'str' object has no attribute 'right'

In [25]:
setup.rjust(39)

'              a duck goes into a bar...'

In [26]:
setup.replace('a','abc',100)

'abc duck goes into abc babcr...'

In [27]:
list('akitoshi koumura')

['a',
 'k',
 'i',
 't',
 'o',
 's',
 'h',
 'i',
 ' ',
 'k',
 'o',
 'u',
 'm',
 'u',
 'r',
 'a']

In [28]:
print(list('akitoshi koumura'))

['a', 'k', 'i', 't', 'o', 's', 'h', 'i', ' ', 'k', 'o', 'u', 'm', 'u', 'r', 'a']


In [29]:
marxes = ['Groucho','Chico','Harpo']

In [30]:
marxes

['Groucho', 'Chico', 'Harpo']

In [31]:
marxes
print(marxes)

['Groucho', 'Chico', 'Harpo']


In [32]:
print(marxes)

['Groucho', 'Chico', 'Harpo']


In [33]:
'k,'.join(marxes)

'Grouchok,Chicok,Harpo'

In [34]:
a='kk,'join(marxes)

SyntaxError: invalid syntax (<ipython-input-34-54acc255f868>, line 1)

In [35]:
a='kk,'.join(marxes)

In [36]:
a

'Grouchokk,Chicokk,Harpo'

In [37]:
print(a)

Grouchokk,Chicokk,Harpo


In [38]:
marxes.sort()

In [39]:
marxes

['Chico', 'Groucho', 'Harpo']

In [40]:
numbers=[1,2,1,22,31,43.9,21.1,'a']

In [41]:
numbers

[1, 2, 1, 22, 31, 43.9, 21.1, 'a']

In [42]:
numbers.sort()

TypeError: '<' not supported between instances of 'str' and 'float'

In [43]:
numbers.remove('a')

In [44]:
numbers

[1, 1, 2, 21.1, 22, 31, 43.9]

In [45]:
numbers.sort()

In [46]:
numbers

[1, 1, 2, 21.1, 22, 31, 43.9]

In [47]:
a=[1,2,3]
b=a

In [48]:
c=a.copy()
d=list(a)
e=a[:]

In [49]:
c
d
e

[1, 2, 3]

In [50]:
print(a,b,c,d,e)

[1, 2, 3] [1, 2, 3] [1, 2, 3] [1, 2, 3] [1, 2, 3]


In [51]:
a[0]='aki'
print(a,b,c,d,e)

['aki', 2, 3] ['aki', 2, 3] [1, 2, 3] [1, 2, 3] [1, 2, 3]


In [52]:
tuple(a)

('aki', 2, 3)

In [53]:
b=tuple(a)

In [54]:
b

('aki', 2, 3)

In [55]:
b(1)

TypeError: 'tuple' object is not callable

In [56]:
b[0]

'aki'

In [57]:
lol={['c':'d'], ['a':'B'],['e':'f'] }

SyntaxError: invalid syntax (<ipython-input-57-a78c415c0dce>, line 1)

In [58]:
lol={['c','d'], ['a','B'],['e','f'] }

TypeError: unhashable type: 'list'

In [59]:
lol=[['c','d'], ['a','B'],['e','f'] ]


In [60]:
lol

[['c', 'd'], ['a', 'B'], ['e', 'f']]

In [61]:
dict(lol)

{'a': 'B', 'c': 'd', 'e': 'f'}

In [62]:
pythons={'a':'b','c':'d','e':'f','a':'ee'}

In [63]:
pythons


{'a': 'ee', 'c': 'd', 'e': 'f'}

In [64]:
pythons.clear()

In [65]:
pythons

{}

In [66]:
pythons={'a':'b','c':'d','e':'f','a':'ee'}

In [67]:
pythons


{'a': 'ee', 'c': 'd', 'e': 'f'}

In [68]:
pythons in 'a'

TypeError: 'in <string>' requires string as left operand, not dict

In [69]:
'a' in pythons

True

In [70]:
'ee' in pythons

False

In [71]:
pythons.get('a ', 'Not a python')

'Not a python'

In [72]:
pythons.get('b','not a python')

'not a python'

In [73]:
pythons.get('c','not a python')

'd'

In [74]:
pythons.keys()

dict_keys(['a', 'c', 'e'])

In [75]:
pythons.values()


dict_values(['ee', 'd', 'f'])

In [77]:
1+2+3+\
4+5

15

In [83]:
disaster=False
if disaster:
    print('woe!')
    else:
        print('wii!')

SyntaxError: invalid syntax (<ipython-input-83-3cee3cc4301d>, line 4)

In [82]:
disaster=False
if disaster:
    print('woe!')
else:
        print('wii!')

wii!


In [81]:
disaster=False
if disaster:
    print('woe!')
else:
    print('wii!')

wii!


In [86]:
color='puce'
if color == 'red':
    print('its a red')
elif color == 'green':
    print('its green')
else:
    print('ive never heard of the color',color)

ive never heard of the color puce


In [88]:
count = 1
while count <= 5:
    print(count)
    count += 1

1
2
3
4
5


In [89]:
count = 1
while count <= 5:
    print(count)
    count += 1

1
2
3
4
5


In [90]:
1+2

3

In [91]:
while True:
    stuff=input('string to capitalize [type q to quit]:')
    if stuff == 'q':
        break
    print(stuff.capitalize())

string to capitalize [type q to quit]:type
Type
string to capitalize [type q to quit]:c
C
string to capitalize [type q to quit]:q


In [92]:
rabbits = ['Flopsy', 'Mopsy','Cottontail']
for rabbit in rabbits:
    print(rabbit)

Flopsy
Mopsy
Cottontail


In [95]:
english ='monday','tuesday','wednesday','thursday'
french='lundi','mardi','mercredi'


In [96]:
list(zip(english,french))

[('monday', 'lundi'), ('tuesday', 'mardi'), ('wednesday', 'mercredi')]

In [97]:
dict(zip(english,french))

{'monday': 'lundi', 'tuesday': 'mardi', 'wednesday': 'mercredi'}

In [98]:
zip(english,french)

In [99]:
for x in range(3):
    print(x)

0
1
2


In [101]:
number_list=[]
for number in range(1,6):
    number_list.append(number)
number_list

[1, 2, 3, 4, 5]

In [102]:
number=[number for number in range(1,7)]

In [103]:
number

[1, 2, 3, 4, 5, 6]

In [104]:
number = [abc for number in range(1,8)]

NameError: name 'abc' is not defined

In [105]:
number = [abc*2 for abc in range(1,8)]

In [106]:
number


[2, 4, 6, 8, 10, 12, 14]

In [108]:
rows=range(1,100)
cols=range(2,50)
cells=[(row,col) for row in rows if row % 2 ==1 for col in cols if col % 2 == 0]
cells

[(1, 2),
 (1, 4),
 (1, 6),
 (1, 8),
 (1, 10),
 (1, 12),
 (1, 14),
 (1, 16),
 (1, 18),
 (1, 20),
 (1, 22),
 (1, 24),
 (1, 26),
 (1, 28),
 (1, 30),
 (1, 32),
 (1, 34),
 (1, 36),
 (1, 38),
 (1, 40),
 (1, 42),
 (1, 44),
 (1, 46),
 (1, 48),
 (3, 2),
 (3, 4),
 (3, 6),
 (3, 8),
 (3, 10),
 (3, 12),
 (3, 14),
 (3, 16),
 (3, 18),
 (3, 20),
 (3, 22),
 (3, 24),
 (3, 26),
 (3, 28),
 (3, 30),
 (3, 32),
 (3, 34),
 (3, 36),
 (3, 38),
 (3, 40),
 (3, 42),
 (3, 44),
 (3, 46),
 (3, 48),
 (5, 2),
 (5, 4),
 (5, 6),
 (5, 8),
 (5, 10),
 (5, 12),
 (5, 14),
 (5, 16),
 (5, 18),
 (5, 20),
 (5, 22),
 (5, 24),
 (5, 26),
 (5, 28),
 (5, 30),
 (5, 32),
 (5, 34),
 (5, 36),
 (5, 38),
 (5, 40),
 (5, 42),
 (5, 44),
 (5, 46),
 (5, 48),
 (7, 2),
 (7, 4),
 (7, 6),
 (7, 8),
 (7, 10),
 (7, 12),
 (7, 14),
 (7, 16),
 (7, 18),
 (7, 20),
 (7, 22),
 (7, 24),
 (7, 26),
 (7, 28),
 (7, 30),
 (7, 32),
 (7, 34),
 (7, 36),
 (7, 38),
 (7, 40),
 (7, 42),
 (7, 44),
 (7, 46),
 (7, 48),
 (9, 2),
 (9, 4),
 (9, 6),
 (9, 8),
 (9, 10),
 (9, 12),


In [110]:
word ='ajdkafj;jaksdjfa;'
letters={letter:word.count(letter) for letter in word}

In [111]:
letters

{';': 2, 'a': 4, 'd': 2, 'f': 2, 'j': 4, 'k': 2, 's': 1}

In [112]:
sets = set('ajdkafj;jaksdjfa;')
sets

{';', 'a', 'd', 'f', 'j', 'k', 's'}

In [115]:
def do_nothing():
    return 2+2

In [116]:
do_nothing()

4

In [117]:
def echo(a):
    print(a,a)

In [118]:
echo('toshi')

toshi toshi


In [119]:
def echoo(b):
    print(b,b)

In [120]:
echoo('toshi')

toshi toshi


In [121]:
def jkl(c)

SyntaxError: invalid syntax (<ipython-input-121-7ce37e7a3db6>, line 1)

In [122]:
def jkl(c):
    return(c + c)

In [123]:
jkl('toshi')

'toshitoshi'

In [127]:
def work(arg):
    result=[]
    result.append(arg)
    return result

In [128]:
work([1,2,3])

[[1, 2, 3]]

In [129]:
work('abc')

['abc']

In [130]:
def work(arg,result=[]):
    result.append(arg)
    return result

In [131]:
work('abc')

['abc']

In [132]:
work('abc')

['abc', 'abc']

In [134]:
def echo(anything):
    'echoは、与えられた入力引数を返す'
    return anything

In [135]:
help(echo)

Help on function echo in module __main__:

echo(anything)
    echoは、与えられた入力引数を返す



In [136]:
print(echo.__echo__)

AttributeError: 'function' object has no attribute '__echo__'

In [137]:
print(echo.__doc__)

echoは、与えられた入力引数を返す


In [139]:
def echo(anything):
    '''
    echoは、与えられた入力引数を返す
    '''
    return anything

In [140]:
globals()


{'In': ['',
  'google=10**100\ngoogle',
  'google* google',
  "'cracle'",
  "'''poem\npoek\npoek'''",
  "'poem\npoek\npoek'",
  "'''poem'''",
  "'''poem\n    poek\n            poek'''",
  'a=1\na',
  'a+=1\na',
  'b+=1\nb',
  "a=['b','c','ef']",
  "a.split(',')",
  "','.join(a)",
  "print(','.join(a)\n     )",
  "setup = 'a duck goes into a bar...'",
  'setup',
  'print(setup\n     )',
  "setup.strip('.')",
  'setup.capitalize',
  'setup.capitalize()',
  'setup.title()',
  'setup.upper()',
  'setup.center(30)',
  'setup.right(30)',
  'setup.rjust(39)',
  "setup.replace('a','abc',100)",
  "list('akitoshi koumura')",
  "print(list('akitoshi koumura'))",
  "marxes = ['Groucho','Chico','Harpo']",
  'marxes',
  'marxes\nprint(marxes)',
  'print(marxes)',
  "'k,'.join(marxes)",
  "a='kk,'join(marxes)",
  "a='kk,'.join(marxes)",
  'a',
  'print(a)',
  'marxes.sort()',
  'marxes',
  "numbers=[1,2,1,22,31,43.9,21.1,'a']",
  'numbers',
  'numbers.sort()',
  "numbers.remove('a')",
  'numbers',
  

In [141]:
def good():
    return ['Harry', 'Ron', 'Hermione']

In [142]:
good()


['Harry', 'Ron', 'Hermione']

In [173]:
def get_odds():
    for x in range(1, 10, 2):
        yield x

In [174]:
get_odds()


<generator object get_odds at 0x1080726d0>

In [185]:
z = get_odds()

In [186]:
z

<generator object get_odds at 0x108072db0>

In [187]:
for count, x in enumerate(z):
    if count == 2:
        print ("the third number is :", x)

the third number is : 5


In [160]:
for x in z:
    print(x)

In [178]:
abc=[1,2,3,4,5,6,7,8]

In [181]:
for x in enumerate (abc,1):
    print (x)

(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 5)
(6, 6)
(7, 7)
(8, 8)


In [294]:
def test(func):
    def newfunction(*args, **kwargs):
        print('start')
        result = func(*args, **kwargs)# ここで関数が実行される。add_intsではprint(a+b)もここで実行される。
        print('end') 
        return result
         
    return newfunction

In [318]:
def add_ints(a,b):
    print (a + b)
    return a+b #returnで下のfaaに値が入る。

In [319]:
faa=add_ints(2,3)

5


In [320]:
cooler_add_ints=test(add_ints)

In [321]:
cooler_add_ints(2,3)

start
5
end


5

In [322]:
def add_ints(a,b):
    print (a+b)

In [323]:
add_ints(2,3)

5


In [324]:
faa

5

In [310]:
type(faa)

int

In [328]:
class OopsException(Exception):
    pass

In [329]:
try:
    raise OopsException('panic')
except OopsException as exc:
    print(exc)

panic


import hello
description = hello.get_description()
print('todays weather:', description)

標準ふぁあｄふぁｆ
\begin{align}
\sqrt{2x-1} 
# aafad
* afdjkf;a
\\\fdafkjak\\\
```fdafl;ajfklj```


In [335]:
%pwd

'/Users/km/pystudy'

In [336]:
!pwd

/Users/km/pystudy


In [337]:
%time sum(range(100000))

CPU times: user 2.35 ms, sys: 53 µs, total: 2.4 ms
Wall time: 2.41 ms


4999950000

In [338]:
%ls

Untitled.ipynb                  introduction_to_ml_with_python/
__pycache__/                    python3entry.ipynb
hello.py
